### ISSUE TITLE
Buffered or unbuffered channels?

### ISSUE THREAD

**Issue by Meshkati** [arcana261/ubroker#23]
Hi, I have a problem with the channel that we give to the consumers by the Delivery method.
The problem comes with the behavior of the broker.
If we use an unbuffered channel, then for each push to the channel, someone has to consume an item from it, so I think that the producers are blocked till someone consumes.
If we use a buffered channel, then it's ok and no one is blocked, but we have to set a capacity for our buffered channel.
Which one of these implementations is more correct? and which one we have to implement😀?

**Comment by arcana261** [comment]
Thank you for cleverly spotting this quirk! It is possible to use unbuffered channels, which is more correct but also more complicated to implement because of blocking per se. For our exercise ill leave this decision to you, we'll accept both implementations.
